-- Dans Supabase SQL Editor
TRUNCATE TABLE document_items CASCADE;
TRUNCATE TABLE documents CASCADE;
TRUNCATE TABLE stock_movements CASCADE;
TRUNCATE TABLE client_payments CASCADE;
TRUNCATE TABLE supplier_payments CASCADE;
TRUNCATE TABLE sale_items CASCADE;
TRUNCATE TABLE sales CASCADE;
TRUNCATE TABLE purchase_items CASCADE;
TRUNCATE TABLE purchases CASCADE;
TRUNCATE TABLE stock CASCADE;